spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: ivan
    password: 31165119221
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
server:
  port: 8080

#logging:
#  level:
#    org:
#      jooq:
#        tools:
#          LoggerListener=DEBUG: